export interface CarDetail{
    carId: number,
    brandName: string,
    brandId: number,                     
    modelName: string,
    modelId: number,                         
    categoryName: string,
    categoryId: number,                     
    gearName: string,
    gearId: number,                        
    colorName: string,
    colorId: number,                         
    segmentName: string,
    segmentId: number,                                                 
    fuelName: string,
    fuelId: number,                        
    conditionName: string,
    conditionId: number,
    imagePath: string[],
    carImageId: number,           
    dailyPrice: number,
    modelYear: number,
}